config = {"h_dim": 8,
          "z_dim": 128,
          "epochs": 500,
          "pre_epochs": 0,
          "net_type": "alt",
          "batch_size": 32,
          "conv_kernel_size": [6,6],
          "kernel_init": "TruncatedNormal",
          "sigma_z": 1.,
          "ae_lr": 1e-4,
          "ae_dec_steps": 9600,
          "ae_dec_rate": 0.9,
          "loc_train_array": "./data/first_8192_samples.npy",
          "loc_test_array": "./data/last_2048_samples.npy",
          "lambda": 100.,
          "c_weight": .5}
