config = {"h_dim": 32,
          "z_dim": 8,
          "epochs": 1000,
          "pre_epochs": 0,
          "net_type": "new_alt",
          "batch_size": 32,
          "conv_kernel_size": [6,6],
          "kernel_init": "TruncatedNormal",
          "sigma_z": 1.,
          "ae_lr": 1e-3,
          "ae_dec_steps": 9600,
          "ae_dec_rate": 0.8,
          "loc_train_array": "/home/giovanni_bindi41/src/data/4096_samples.npy",
          "loc_test_array": "/home/giovanni_bindi41/src/data/1024_samples.npy",
          "lambda": 100.}